FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml ./
COPY app ./app
COPY celery.sh ./celery.sh

RUN chmod +x /app/celery.sh \
    && pip install --no-cache-dir .

CMD ["./celery.sh"]
